name: Go

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set Install Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20

            - name: Run Test
              run: go test -v ./...